[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript", "--use-tabs", "true", "--tab-width", "2"] }
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "text-files"
scope = "source.txt"
file-types = ["txt"]
indent = { tab-width = 2, unit = "\t" }

